-- AlterTable
ALTER TABLE `users` ADD COLUMN `direction` ENUM('LTR', 'RTL', 'SYSTEM') NOT NULL DEFAULT 'SYSTEM',
    ADD COLUMN `facebook` VARCHAR(191) NULL,
    ADD COLUMN `linkedIn` VARCHAR(191) NULL,
    ADD COLUMN `profileImage` VARCHAR(191) NULL,
    ADD COLUMN `skype` VARCHAR(191) NULL,
    ADD COLUMN `twoFactorType` ENUM('DISABLED', 'EMAIL', 'GOOGLE') NOT NULL DEFAULT 'DISABLED';
